### ISSUE TITLE
DVBViewer addon cant connect to Recordiung Service

### ISSUE THREAD

**Issue by bambamboole** [manuelm/xbmc-pvr-addons#6]
HI Manuel,

I've got a working Recording Service (1.30.1.0 beta) on a windows 8.1 machine. another machine works great with DVBViewer Pro. For the bedroom i take a Raspberry Pi with openelec 5+kodi 14 and your pvr addon  (v1.9.23) but i only get the note that the pvr addon is unable to connect to the recording service.

The network settings are fine...

please help me :-)

**Comment by manuelm** [comment]
Try turning off the windows firewall. If that works, add an exception/allow-rule for the recording service process and enable the firewall again.
In general 1.30.1.0 works fine here.

**Comment by bambamboole** [comment]
it was the # in the password which doesnt worked but thx

**Comment by manuelm** [comment]
I've duplicated the issue in the new pvr repo. Will close this one.
Thanks for reporting.
