### ISSUE TITLE
tv server off > cant connect to Recordiung Service popups constantly

### ISSUE THREAD

**Issue by Gofel** [manuelm/xbmc-pvr-addons#7]
Sometimes my tv server is off and i just want to watch a movie on kodi. But the popup tells me constantly that my connection is broken, so i can´t watch my movie until i disable Live TV. Is it possible to let the popup only come up when the status change. thank you.

**Comment by manuelm** [comment]
This has been fixed in 1.9.28 (see http://forum.kodi.tv/showthread.php?tid=140645&pid=1363784#pid1363784)

There will be still a notification about lost connection to the backend every 30 seconds from Kodi itself. This notification can be disabled in Kodi`s settings.

**Comment by Gofel** [comment]
The notification in kodi is disabled and looks different when I turn it on. Here is the notification i can´t disable: https://www.dropbox.com/s/fzxazs5z9wiluc8/dvbviewer.PNG?dl=0

**Comment by manuelm** [comment]
You're running 1.x.27 or below. The notification has been removed in 1.x.28

**Comment by Gofel** [comment]
Kodi ver. 14.0
dvbviewer client 1.9.23
https://www.dropbox.com/s/r67k3zpctuybayj/ver.PNG?dl=0

**Comment by Gofel** [comment]
Thats it, thx
